### ISSUE TITLE
Step 10: Add override class spacing on DD Guarantee list

### ISSUE THREAD

**Issue by mrmjprice** [wmcadigital/wmn-covid19-directdebit#24]
As per #21

**Comment by daylesalmon** [comment]
I believe this is done, can you recheck and sign off @mrmjprice

**Comment by mrmjprice** [comment]
<img width="882" alt="Screenshot 2020-05-13 at 16 08 09" src="https://user-images.githubusercontent.com/10854265/81830425-f1c03e00-9533-11ea-9b27-19e32f81cf7b.png">

Still a wall of text 😢
