### ISSUE TITLE
Step 10: Add more spacing between DD Guarantee and H3

### ISSUE THREAD

**Issue by mrmjprice** [wmcadigital/wmn-covid19-directdebit#25]

**Comment by daylesalmon** [comment]
I believe this is done, can you recheck and sign off @mrmjprice

**Comment by mrmjprice** [comment]
Sadly not.

Please can you add another 2 line breaks between the Direct Debit guarantee unordered list and "Bank or building society account details" H3?

**Comment by mrmjprice** [comment]
Old, no space: <img width="905" alt="Screenshot 2020-05-13 at 16 09 20" src="https://user-images.githubusercontent.com/10854265/81830615-34821600-9534-11ea-85b5-5c7c787d9927.png">

New, with space: 
<img width="911" alt="Screenshot 2020-05-13 at 16 09 53" src="https://user-images.githubusercontent.com/10854265/81830640-3e0b7e00-9534-11ea-91ec-3397871b7a3d.png">
