### ISSUE TITLE
Success page: Print CSS (nice-to-have)

### ISSUE THREAD

**Issue by mrmjprice** [wmcadigital/wmn-covid19-directdebit#27]
Some user feedback from refunds form was users would like to print the page. Our CSS goes a bit wonky.

Could we do some print CSS to:
- [x] Turn logo black
- [x] Hide BETA bar
- [x] Hide Breadcrumbs
- [x] In success banner, make tick black
- [x] In success banner, make text black

**Comment by daylesalmon** [comment]
Closed with #76
